name: PyPi Release

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pywiegandpi
    permissions:
      id-token: write
    steps:
    - name: Install dependencies
      run: pip install build
    - name: Build package
      run: python -m build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1